apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: kafka
spec:
  interval: 5m
  chart:
    spec:
      chart: kafka
      version: "26.8.5"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: kafka
      interval: 1m
  values:
    # Konfigurera för lokal utveckling
    replicaCount: 1
    deleteTopicEnable: true
    autoCreateTopicsEnable: true
    numPartitions: 3
    defaultReplicationFactor: 1
    
    # Resurs-begränsningar för lokal miljö
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    
    # Persistent storage
    persistence:
      enabled: true
      size: 2Gi
    
    # Zookeeper konfiguration (enklare för demo)
    zookeeper:
      enabled: true
      replicaCount: 1
      persistence:
        enabled: true
        size: 1Gi
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    
    # Externa åtkomst (för demo)
    service:
      type: ClusterIP
      ports:
        client: 9092
    
    # Kafka UI (valfritt för demo)
    externalAccess:
      enabled: false
    
    # Monitoring
    metrics:
      kafka:
        enabled: true
      jmx:
        enabled: true