apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: strimzi-kafka-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: flux-system
      interval: 1m
  values:
    # Övervaka alla namespaces (eller specificera kafka namespace)
    watchAnyNamespace: false
    watchNamespaces: 
      - default
    
    # Resurs-begränsningar för lokal miljö
    resources:
      limits:
        cpu: 200m
        memory: 384Mi
      requests:
        cpu: 100m
        memory: 256Mi
    
    # Loggnivå
    logLevel: INFO
    
    # Feature gates (aktivera önskade funktioner)
    #featureGates: "+UseKRaft,+KafkaNodePools"